

variables_to_discard = [
    'totrev',
    'avgrev',
    'avg3rev',
    'avg6rev',
    'ccrndmou_Mean',
    'cc_mou_Mean',
    'mou_opkd_Mean',
    'mou_pead_Mean',
    'mou_cdat_Mean',
    'mou_opkv_Mean',
    'totmou',
    'avgmou',
    'avg3mou',
    'avg6mou',
    'mou_peav_Mean',
    'avgqty',
    'avg3qty',
    'avg6qty',
    'drop_blk_Mean',
    'plcd_dat_Mean',
    'unan_vce_Mean',
    'peak_vce_Mean',
    'opk_vce_Mean',
    'uniqsubs',
    'models',
    'plcd_vce_Mean',
    'comp_vce_Mean',
    'inonemin_Mean',
    'peak_dat_Mean',
    'recv_vce_Mean',
    'owylis_vce_Mean',
    'attempt_Mean']